### ISSUE TITLE
Add a fold method as another way to unwrap result

### ISSUE THREAD

**Issue by blork** [3squared/PeakResult#1]
I've been using [this Result library](https://github.com/kittinunf/Result) in Kotlin and I'm quite fond of the `fold` method:

```kotlin
//fold is there, if you want to handle both success and failure
result.fold({ value ->
    //do something with value
}, { error ->
    //do something with error
})
```

Something similar could be nice here. Especially if we could allow `fold` to return a value, and you could do things like this:

```swift
let a: Bool = result.fold({ value in
    return true
}, { error in
    return false
})
```

**Comment by lukestringer90** [comment]
Looks nice. I guess it would be syntactic sugar for this sort of thing:

```
if let value = try? result.resolve() {

}
else {

}
```

**Comment by blork** [comment]
Now you say that, I'm wondering if it adds much...(I forgot you can `try?` resolve them like that in Swift).

**Comment by blork** [comment]
Added an implementation of this. I suppose it is nicer than the `if let` thing alternative as you get access to the error and can also return a value, making it quite neat in certain circumstances.

**Comment by blork** [comment]
Made a pull request (#3)
